[package]
name = "derive-hex"
version = "0.1.0"
authors = ["zer0 <matteo@dusk.network>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.24"
quote = "1.0.8"
syn = "1.0.58"
